model = "gpt-5.2-codex"
model_reasoning_effort = "high"

[sandbox_workspace_write]
network_access = true 

[projects."/home/nia"]
trust_level = "trusted"

[projects."/home/nia/ghq/github.com/niadot/dotfiles"]
trust_level = "trusted"
