model = "gpt-5.3-codex"
model_reasoning_effort = "high"
personality = "pragmatic"

[sandbox_workspace_write]
network_access = true 

[projects."/home/nia"]
trust_level = "trusted"

[projects."/home/nia/ghq/github.com/niadot/dotfiles"]
trust_level = "trusted"

[projects."/home/nia/ghq/github.com/niadot"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"
